name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: curl -X POST "https://api.render.com/deploy/srv-d7h17sosfn5c73e4u0b0?key=e8qpQBIkZ58"